name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
# on:
#   release:
#     types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # registry-url: 'https://registry.npmjs.org'
          # scope: '@kailash-jakhar'
      - run: npm ci
      - run: npm run rollup
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
